//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }

        private string _productPhoto;
        public string ProductPhoto {
            get
            {
                if (string.IsNullOrEmpty(_productPhoto))
                    return "/Resources/picture.png";
                else
                    return "/Resources/" + _productPhoto;
            }
            set
            {
                _productPhoto = value;
            }
        }
        public string ProductManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductQuantityInStock { get; set; }
    }
}
