//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piter_Retail_Central_Server.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public int ID_Data { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public long AmountOfFuel { get; set; }
        public int Station_ID { get; set; }
        
        [JsonIgnore]
        public virtual Station Station { get; set; }
    }
}
